### ISSUE TITLE
Add New Restriction page uses "Post" terminology instead of "Restriction" terminology

### ISSUE THREAD

**Issue by raamdev** [websharks/woocommerce-s2member-x#3]
When creating a new Restriction, the Dashboard message says "Post published" instead of "Restriction created".

![2016-05-25_12-04-08](https://cloud.githubusercontent.com/assets/53005/15547281/2e0dd0b4-2271-11e6-8706-a65cc16e3fec.png)

Along the same lines, it would make more sense if the "Publish" button said "Create Restriction":

![2016-05-25_12-06-01](https://cloud.githubusercontent.com/assets/53005/15547274/21f4afd2-2271-11e6-9052-e03cd0ff7709.png)

**Comment by jaswrks** [comment]
Thank you! :-) Updated in https://github.com/websharks/s2member-x-pro/commit/f16b5d9b9bbddac76cdb843e41c14e0c7c6d5860
